//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFarming
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Crop()
        {
            this.MajorProducers = new HashSet<MajorProducer>();
            this.Seeds = new HashSet<Seed>();
        }
    
        public int id { get; set; }
        public string CropName { get; set; }
        public string CropDesc { get; set; }
        public Nullable<bool> Kharif { get; set; }
        public Nullable<bool> Rabi { get; set; }
        public Nullable<bool> Zaid { get; set; }
        public int type_id { get; set; }
        public string CropImage { get; set; }
        public string Temp { get; set; }
        public string RainFall { get; set; }
        public string SoilType { get; set; }
        public Nullable<int> HighestProducers { get; set; }
        public string LandPreparation { get; set; }
        public string SowingMethod { get; set; }
        public string Harvesting { get; set; }
    
        public virtual CropType CropType { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MajorProducer> MajorProducers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seed> Seeds { get; set; }
    }
}
