//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFarming
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fertilizer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fertilizer()
        {
            this.Quotations = new HashSet<Quotation>();
        }
    
        public int id { get; set; }
        public int dealer_id { get; set; }
        public int crop_id { get; set; }
        public string FertilizerName { get; set; }
        public string FertilizerImage { get; set; }
        public string Material { get; set; }
        public string PackType { get; set; }
        public string PackSize { get; set; }
        public string Features { get; set; }
        public string Solubility { get; set; }
        public string Doses { get; set; }
        public string PHvalue { get; set; }
        public string HowToUse { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotation> Quotations { get; set; }
    }
}
