//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFarming
{
    using System;
    using System.Collections.Generic;
    
    public partial class MajorProducer
    {
        public int id { get; set; }
        public int crop_id { get; set; }
        public int state_id { get; set; }
    
        public virtual Crop Crop { get; set; }
        public virtual State State { get; set; }
    }
}
