//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFarming
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartFarmingEntities : DbContext
    {
        public SmartFarmingEntities()
            : base("name=SmartFarmingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<Crop> Crops { get; set; }
        public virtual DbSet<CropType> CropTypes { get; set; }
        public virtual DbSet<Faq> Faqs { get; set; }
        public virtual DbSet<Fertilizer> Fertilizers { get; set; }
        public virtual DbSet<MajorProducer> MajorProducers { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Pesticide> Pesticides { get; set; }
        public virtual DbSet<Quotation> Quotations { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SeedImage> SeedImages { get; set; }
        public virtual DbSet<Seed> Seeds { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tractor> Tractors { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<SeedFaq> SeedFaqs { get; set; }
    }
}
