//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFarming
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation
    {
        public int id { get; set; }
        public Nullable<int> seed_id { get; set; }
        public Nullable<int> pesticide_id { get; set; }
        public Nullable<int> fertilizer_id { get; set; }
        public int dealer_id { get; set; }
        public int Quantity { get; set; }
        public string Unit { get; set; }
        public string ContactNo { get; set; }
    
        public virtual Fertilizer Fertilizer { get; set; }
        public virtual Pesticide Pesticide { get; set; }
        public virtual Seed Seed { get; set; }
        public virtual User User { get; set; }
    }
}
