//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFarming
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seed()
        {
            this.Quotations = new HashSet<Quotation>();
            this.SeedImages = new HashSet<SeedImage>();
        }
    
        public int id { get; set; }
        public int crop_id { get; set; }
        public int dealer_id { get; set; }
        public string SeedName { get; set; }
        public string Season { get; set; }
        public string PestTolerance { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Duration { get; set; }
        public Nullable<int> MinQuentity { get; set; }
        public string Description { get; set; }
        public string PacketSize { get; set; }
        public string GrowthHabit { get; set; }
        public string PositiveFactor { get; set; }
        public string NegativeFactor { get; set; }
        public string Temp { get; set; }
        public string Fertilizer { get; set; }
        public string Height { get; set; }
        public Nullable<int> SeedsPerPacket { get; set; }
    
        public virtual Crop Crop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotation> Quotations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeedImage> SeedImages { get; set; }
        public virtual User User { get; set; }
    }
}
