//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFarming
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeedImage
    {
        public int id { get; set; }
        public int seed_id { get; set; }
        public string Image { get; set; }
    
        public virtual Seed Seed { get; set; }
    }
}
