//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFarming
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tractor
    {
        public int id { get; set; }
        public int dealer_id { get; set; }
        public string ModelName { get; set; }
        public string TractorImage { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string Clutch { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> NoOfCylinder { get; set; }
        public Nullable<int> HpCategory { get; set; }
        public string EngineRatedRPM { get; set; }
        public string Cooling { get; set; }
        public string AirFilter { get; set; }
        public string Brake { get; set; }
        public string Battery { get; set; }
        public string GearBox { get; set; }
        public string Steering { get; set; }
        public string FuelTank { get; set; }
        public string Accessories { get; set; }
        public string Features { get; set; }
        public Nullable<int> Warranty { get; set; }
        public string Status { get; set; }
        public Nullable<int> TotalWeight { get; set; }
        public Nullable<int> GroundClearance { get; set; }
        public Nullable<int> TurningRadius { get; set; }
    
        public virtual User User { get; set; }
    }
}
